### ISSUE TITLE
Parallel CP2K on Windows

### ISSUE THREAD

**Issue by maurosgroi** [brhr-iwao/CP2K_for_Windows#1]
Dear brhr-iwao,
My name is Mauro Sgroi.
I'm compiling a paraller version of cp2k on windows.
I succeeded to compile the code with no Sirius.
Now I'm struggling to compile Sirius and I've problem to get the SpFFT recognized by cmake in Sirius.
Could you please share your cmake command to compile Sirius and SpFFT?
Which version of SpFFT have you used?

Thanks a lot and best regards,
Mauro Sgroi.

**Comment by brhr-iwao** [comment]
Dear Mauro,

I ran cmake for spfft-0.9.10 on cygwin bash with:

mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DSPFFT_FORTRAN=ON　-DSPFFT_OMP=ON -DSPFFT_MPI=ON -DSPFFT_SINGLE_PRECISION=OFF -DCMAKE_INSTALL_PREFIX=/usr/local

This is the default settings except the fortran binding.
The option "-DSPFFT_MPI=ON" is necessary. If this flag is OFF, sirius compilation fails with the error:
/src/function3d/smooth_periodic_function.hpp:291:48: error: ‘class spfft::Transform’ has no member named ‘communicator’

After the spfft installation ("make install"), I ran cmake for sirius with:

mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX="usr/local/sirius" -DCMAKE_CXX_COMPILER="/bin/g++"

If the cmake is succeded, some directories and files are generated in the "build" directory.
Next I edited "flags.make" and "link.txt" (text files) in build/src/CMakeFiles/sirius.dir, build/apps/atoms/CMakeFiles/atoms.dir, build/apps/dft_loop/CMakeFiles/sirius.scf.dir and build/apps/utils/CMakeFiles/unit_cell_tools.dir.

You may find "CXX_INCLUDES=...-isystem /cygdrive/c/MinGW/include/" on each flags.make.
This specification caused many many errors such as "cwchar error ::fgets has not been declared" etc during sirius compilation.
I deleted the string "-isystem /cygdrive/c/MinGW/include/", then these errors disappeared.

You also may find "... -L/usr/lib/gcc/i686-pc-cygwin/9.3.0/ ... /cygdrive/c/MinGW/lib/libgdi32.a ... /cygdrive/c/MinGW/lib/libxc.a ..." on each link.txt. 
If you have installed MinGW, there is probably no problem. But if not, this specification causes link errors.
I edited the string to "... /lib/w32api/libgdi32.a ... /home/user/libxc-4.0.4/src/.libs/libxc.a" to specify the actually existing libraries.

This is a very awkward way. It should be edited the CMakeLists.txt or something else for fundamental solution, but I can't find an alternative way.

Hope this helps,

Regards,

brhr-iwao

**Comment by maurosgroi** [comment]
Dear brhr-iwao,
thanks a lot for the help.
I was able to compile cp2k.
Best regards,
Mauro Sgroi.

**Comment by brhr-iwao** [comment]
Closing
